# Generated by Django 5.2.6 on 2025-09-18 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("user", "0002_user_note_alter_customer_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("delivery_predict", models.DateField()),
                ("delivery_actual", models.DateField()),
                (
                    "amount1",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("unit1", models.CharField(blank=True, max_length=5, null=True)),
                ("amount2", models.CharField(blank=True, max_length=10, null=True)),
                ("unit2", models.CharField(blank=True, max_length=1, null=True)),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                ("process", models.CharField(max_length=10)),
                ("workstation", models.CharField(max_length=20)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("remove_at", models.DateTimeField(blank=True, null=True)),
                ("customer_name", models.CharField(max_length=10)),
                ("product_name", models.CharField(max_length=30)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.customer",
                    ),
                ),
                (
                    "formula",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="order.formula",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="order.product",
                    ),
                ),
                (
                    "reviewer1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_reviewer1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_reviewer2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
